server:
  port: 8888

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka


spring:
  application:
    name: gateway-service-wfd
  cloud:
    gateway:
      routes:
        - id: meal-service
          uri: lb://meal-service
          predicates:
            - Path=/meal/**
          filters:
            - RewritePath=/meal/(?<segment>.*), /$\{segment}
        - id: fridge-service
          uri: lb://fridge-service
          predicates:
            - Path=/fridge/**
        - id: shopping-list-service
          uri: lb://shopping-list-service
          predicates:
            - Path=/shoppingList/**
          filters:
            - RewritePath=/shoppingList/(?<segment>.*), /$\{segment}
        - id: django-users
          uri: lb://django-users
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), $\{segment}

        - id: django-chat
          uri: lb://django-chat
          predicates:
            - Path=/chat/**,  /**
          filters:
            - RewritePath=/chat/(?<segment>.*), $\{segment}
