# Generated by Django 4.1 on 2022-08-15 14:49

import chatcomponents.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatcomponents', '0002_rename_userid_person_userid_channels_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
                ('content', models.CharField(max_length=6000)),
                ('postTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='channels',
            name='messages',
            field=djongo.models.fields.ArrayField(default=[], model_container=chatcomponents.models.ChatMessages),
            preserve_default=False,
        ),
    ]
