version: "3.9"
services:

  chat-room-service: 
    build: 
      context: ./Chat Room Service
    depends_on:
      - user-chat-information-db
      - registration-service
    ports:
      - "8000"
    networks:
      - base-net
    deploy:
      replicas: 1
  
  fridge-service:
    build:
      context: ./Fridge Service
    depends_on:
      - registration-service
      - meal-information-db
    ports: 
      - "8080"
    networks:
      - base-net
    deploy:
      replicas: 1

  meal-service:
    build:
      context: ./Meal Service
    depends_on:
      - registration-service
      - meal-information-db
    ports: 
      - "8080"
    networks:
      - base-net
    deploy:
      replicas: 1

  user-service:
    build: 
      context: ./User Service/DjangoUsers
    environment:
      - MYSQL_DBNAME=djangousers
      - MYSQL_USER=djangologin
      - MYSQL_PASS=abcd12@!F
      - MYSQL_HOST=user-sql-db
      - MYSQL_PORT=3306
      - EUREKA_SERVER=http://eureka:8761/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - django-user-db
      - registration-service
      - rabbitmq
    ports: 
      - "8000"
    networks:
      - base-net
    deploy:
      replicas: 1

  shopping-list-service:
    build: 
      context: ./Shopping List Service
    depends_on:
      - registration-service
      - meal-information-db
    ports: 
      - "8080"
    networks:
      - base-net
    deploy:
      replicas: 1

  whatsfordinner-gateway:
    build:
      context: ./WFDGateway
    container_name: "wfd-gateway"
    depends_on:
      - chat-room-service
      - fridge-service
      - meal-service
      - user-service
      - shopping-list-service
    ports:
      - "8888:8888"
    networks:
      - base-net

  registration-service:
    image: "steeltoeoss/eureka-server"
    container_name: "eureka"
    ports:
      - "8761:8761"
    networks:
    - base-net

  meal-information-db:
    image: "mongo:latest"
    container_name: meal_info_db
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=MealInfo
    networks:
      - base-net

  user-chat-information-db:
    image: "mongo:latest"
    container_name: chat_info_db
    ports:
      - "27017"
    networks:
      - base-net

  django-user-db:
    image: "mysql:latest"
    container_name: user-sql-db
    environment:
      - MYSQL_DATABASE=djangousers
      - MYSQL_USER=djangologin
      - MYSQL_PASSWORD=abcd12@!F
      - MYSQL_ROOT_PASSWORD=abcd12@!F
    ports:
      - "3306"
    networks:
      - base-net

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - base-net

networks:
  base-net:
    name: "whatsfordinner"