# Generated by Django 4.1 on 2022-08-06 21:16

import chatcomponents.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('invitedPeople', djongo.models.fields.ArrayField(model_container=chatcomponents.models.Person)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
            ],
        ),
    ]
